n = int(input())
print(' '.join([" @@@   @@@ " for i in range(n)]))
print(' '.join(["@   @ @   @" for i in range(n)]))
print(' '.join(["@    @    @" for i in range(n)]))
print(' '.join(["@         @" for i in range(n)]))
print(' '.join([" @       @ " for i in range(n)]))
print(' '.join(["  @     @  " for i in range(n)]))
print(' '.join(["   @   @   " for i in range(n)]))
print(' '.join(["    @ @    " for i in range(n)]))
print(' '.join(["     @     " for i in range(n)]))